// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.gifdex.feed.defs
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

pub mod favourite;
pub mod get_post;
pub mod get_posts_by_actor;
pub mod get_posts_by_query;
pub mod post;

/// Feed-optimized view of a post with all metadata needed for display in timelines.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct PostFeedView<'a> {
    #[serde(borrow)]
    pub author: crate::net_gifdex::actor::ProfileViewBasic<'a>,
    pub created_at: jacquard_common::types::string::Datetime,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub edited_at: std::option::Option<jacquard_common::types::string::Datetime>,
    pub favourite_count: i64,
    pub indexed_at: jacquard_common::types::string::Datetime,
    #[serde(borrow)]
    pub media: crate::net_gifdex::feed::PostViewMedia<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub tags: std::option::Option<Vec<jacquard_common::CowStr<'a>>>,
    #[serde(borrow)]
    pub title: jacquard_common::CowStr<'a>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub viewer: crate::net_gifdex::feed::ViewerState<'a>,
}

pub mod post_feed_view_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type IndexedAt;
        type Viewer;
        type Author;
        type Uri;
        type FavouriteCount;
        type Title;
        type Media;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type IndexedAt = Unset;
        type Viewer = Unset;
        type Author = Unset;
        type Uri = Unset;
        type FavouriteCount = Unset;
        type Title = Unset;
        type Media = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `indexed_at` field to Set
    pub struct SetIndexedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetIndexedAt<S> {}
    impl<S: State> State for SetIndexedAt<S> {
        type IndexedAt = Set<members::indexed_at>;
        type Viewer = S::Viewer;
        type Author = S::Author;
        type Uri = S::Uri;
        type FavouriteCount = S::FavouriteCount;
        type Title = S::Title;
        type Media = S::Media;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `viewer` field to Set
    pub struct SetViewer<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetViewer<S> {}
    impl<S: State> State for SetViewer<S> {
        type IndexedAt = S::IndexedAt;
        type Viewer = Set<members::viewer>;
        type Author = S::Author;
        type Uri = S::Uri;
        type FavouriteCount = S::FavouriteCount;
        type Title = S::Title;
        type Media = S::Media;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `author` field to Set
    pub struct SetAuthor<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAuthor<S> {}
    impl<S: State> State for SetAuthor<S> {
        type IndexedAt = S::IndexedAt;
        type Viewer = S::Viewer;
        type Author = Set<members::author>;
        type Uri = S::Uri;
        type FavouriteCount = S::FavouriteCount;
        type Title = S::Title;
        type Media = S::Media;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUri<S> {}
    impl<S: State> State for SetUri<S> {
        type IndexedAt = S::IndexedAt;
        type Viewer = S::Viewer;
        type Author = S::Author;
        type Uri = Set<members::uri>;
        type FavouriteCount = S::FavouriteCount;
        type Title = S::Title;
        type Media = S::Media;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `favourite_count` field to Set
    pub struct SetFavouriteCount<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetFavouriteCount<S> {}
    impl<S: State> State for SetFavouriteCount<S> {
        type IndexedAt = S::IndexedAt;
        type Viewer = S::Viewer;
        type Author = S::Author;
        type Uri = S::Uri;
        type FavouriteCount = Set<members::favourite_count>;
        type Title = S::Title;
        type Media = S::Media;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTitle<S> {}
    impl<S: State> State for SetTitle<S> {
        type IndexedAt = S::IndexedAt;
        type Viewer = S::Viewer;
        type Author = S::Author;
        type Uri = S::Uri;
        type FavouriteCount = S::FavouriteCount;
        type Title = Set<members::title>;
        type Media = S::Media;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `media` field to Set
    pub struct SetMedia<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetMedia<S> {}
    impl<S: State> State for SetMedia<S> {
        type IndexedAt = S::IndexedAt;
        type Viewer = S::Viewer;
        type Author = S::Author;
        type Uri = S::Uri;
        type FavouriteCount = S::FavouriteCount;
        type Title = S::Title;
        type Media = Set<members::media>;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type IndexedAt = S::IndexedAt;
        type Viewer = S::Viewer;
        type Author = S::Author;
        type Uri = S::Uri;
        type FavouriteCount = S::FavouriteCount;
        type Title = S::Title;
        type Media = S::Media;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `indexed_at` field
        pub struct indexed_at(());
        ///Marker type for the `viewer` field
        pub struct viewer(());
        ///Marker type for the `author` field
        pub struct author(());
        ///Marker type for the `uri` field
        pub struct uri(());
        ///Marker type for the `favourite_count` field
        pub struct favourite_count(());
        ///Marker type for the `title` field
        pub struct title(());
        ///Marker type for the `media` field
        pub struct media(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct PostFeedViewBuilder<'a, S: post_feed_view_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<crate::net_gifdex::actor::ProfileViewBasic<'a>>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<crate::net_gifdex::feed::PostViewMedia<'a>>,
        ::core::option::Option<Vec<jacquard_common::CowStr<'a>>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
        ::core::option::Option<crate::net_gifdex::feed::ViewerState<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> PostFeedView<'a> {
    /// Create a new builder for this type
    pub fn new() -> PostFeedViewBuilder<'a, post_feed_view_state::Empty> {
        PostFeedViewBuilder::new()
    }
}

impl<'a> PostFeedViewBuilder<'a, post_feed_view_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::Author: post_feed_view_state::IsUnset,
{
    /// Set the `author` field (required)
    pub fn author(
        mut self,
        value: impl Into<crate::net_gifdex::actor::ProfileViewBasic<'a>>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetAuthor<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::CreatedAt: post_feed_view_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetCreatedAt<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: post_feed_view_state::State> PostFeedViewBuilder<'a, S> {
    /// Set the `editedAt` field (optional)
    pub fn edited_at(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Datetime>>,
    ) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `editedAt` field to an Option value (optional)
    pub fn maybe_edited_at(
        mut self,
        value: Option<jacquard_common::types::string::Datetime>,
    ) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::FavouriteCount: post_feed_view_state::IsUnset,
{
    /// Set the `favouriteCount` field (required)
    pub fn favourite_count(
        mut self,
        value: impl Into<i64>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetFavouriteCount<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::IndexedAt: post_feed_view_state::IsUnset,
{
    /// Set the `indexedAt` field (required)
    pub fn indexed_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetIndexedAt<S>> {
        self.__unsafe_private_named.4 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::Media: post_feed_view_state::IsUnset,
{
    /// Set the `media` field (required)
    pub fn media(
        mut self,
        value: impl Into<crate::net_gifdex::feed::PostViewMedia<'a>>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetMedia<S>> {
        self.__unsafe_private_named.5 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: post_feed_view_state::State> PostFeedViewBuilder<'a, S> {
    /// Set the `tags` field (optional)
    pub fn tags(
        mut self,
        value: impl Into<Option<Vec<jacquard_common::CowStr<'a>>>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value.into();
        self
    }
    /// Set the `tags` field to an Option value (optional)
    pub fn maybe_tags(
        mut self,
        value: Option<Vec<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value;
        self
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::Title: post_feed_view_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetTitle<S>> {
        self.__unsafe_private_named.7 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::Uri: post_feed_view_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetUri<S>> {
        self.__unsafe_private_named.8 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::Viewer: post_feed_view_state::IsUnset,
{
    /// Set the `viewer` field (required)
    pub fn viewer(
        mut self,
        value: impl Into<crate::net_gifdex::feed::ViewerState<'a>>,
    ) -> PostFeedViewBuilder<'a, post_feed_view_state::SetViewer<S>> {
        self.__unsafe_private_named.9 = ::core::option::Option::Some(value.into());
        PostFeedViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostFeedViewBuilder<'a, S>
where
    S: post_feed_view_state::State,
    S::IndexedAt: post_feed_view_state::IsSet,
    S::Viewer: post_feed_view_state::IsSet,
    S::Author: post_feed_view_state::IsSet,
    S::Uri: post_feed_view_state::IsSet,
    S::FavouriteCount: post_feed_view_state::IsSet,
    S::Title: post_feed_view_state::IsSet,
    S::Media: post_feed_view_state::IsSet,
    S::CreatedAt: post_feed_view_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> PostFeedView<'a> {
        PostFeedView {
            author: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            edited_at: self.__unsafe_private_named.2,
            favourite_count: self.__unsafe_private_named.3.unwrap(),
            indexed_at: self.__unsafe_private_named.4.unwrap(),
            media: self.__unsafe_private_named.5.unwrap(),
            tags: self.__unsafe_private_named.6,
            title: self.__unsafe_private_named.7.unwrap(),
            uri: self.__unsafe_private_named.8.unwrap(),
            viewer: self.__unsafe_private_named.9.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> PostFeedView<'a> {
        PostFeedView {
            author: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            edited_at: self.__unsafe_private_named.2,
            favourite_count: self.__unsafe_private_named.3.unwrap(),
            indexed_at: self.__unsafe_private_named.4.unwrap(),
            media: self.__unsafe_private_named.5.unwrap(),
            tags: self.__unsafe_private_named.6,
            title: self.__unsafe_private_named.7.unwrap(),
            uri: self.__unsafe_private_named.8.unwrap(),
            viewer: self.__unsafe_private_named.9.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_net_gifdex_feed_defs() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("net.gifdex.feed.defs"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::alloc::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("postFeedView"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "Feed-optimized view of a post with all metadata needed for display in timelines.",
                        ),
                    ),
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("uri"),
                            ::jacquard_common::smol_str::SmolStr::new_static("author"),
                            ::jacquard_common::smol_str::SmolStr::new_static("title"),
                            ::jacquard_common::smol_str::SmolStr::new_static("media"),
                            ::jacquard_common::smol_str::SmolStr::new_static("favouriteCount"),
                            ::jacquard_common::smol_str::SmolStr::new_static("viewer"),
                            ::jacquard_common::smol_str::SmolStr::new_static("createdAt"),
                            ::jacquard_common::smol_str::SmolStr::new_static("indexedAt")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::alloc::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("author"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static(
                                    "net.gifdex.actor.defs#profileViewBasic",
                                ),
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "createdAt",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("editedAt"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "favouriteCount",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                description: None,
                                default: None,
                                minimum: None,
                                maximum: None,
                                r#enum: None,
                                r#const: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "indexedAt",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("media"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static(
                                    "#postViewMedia",
                                ),
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("tags"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Array(::jacquard_lexicon::lexicon::LexArray {
                                description: None,
                                items: ::jacquard_lexicon::lexicon::LexArrayItem::String(::jacquard_lexicon::lexicon::LexString {
                                    description: None,
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                                min_length: None,
                                max_length: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("title"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("uri"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::AtUri,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("viewer"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static("#viewerState"),
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("postView"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "Detailed view of a post, including author information and engagement metrics.",
                        ),
                    ),
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("uri"),
                            ::jacquard_common::smol_str::SmolStr::new_static("author"),
                            ::jacquard_common::smol_str::SmolStr::new_static("title"),
                            ::jacquard_common::smol_str::SmolStr::new_static("media"),
                            ::jacquard_common::smol_str::SmolStr::new_static("favouriteCount"),
                            ::jacquard_common::smol_str::SmolStr::new_static("viewer"),
                            ::jacquard_common::smol_str::SmolStr::new_static("createdAt"),
                            ::jacquard_common::smol_str::SmolStr::new_static("indexedAt")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::alloc::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("author"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static(
                                    "net.gifdex.actor.defs#profileViewBasic",
                                ),
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "createdAt",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("editedAt"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "favouriteCount",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                description: None,
                                default: None,
                                minimum: None,
                                maximum: None,
                                r#enum: None,
                                r#const: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "indexedAt",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("media"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static(
                                    "#postViewMedia",
                                ),
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("tags"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Array(::jacquard_lexicon::lexicon::LexArray {
                                description: None,
                                items: ::jacquard_lexicon::lexicon::LexArrayItem::String(::jacquard_lexicon::lexicon::LexString {
                                    description: None,
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                                min_length: None,
                                max_length: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("title"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("uri"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::AtUri,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("viewer"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static("#viewerState"),
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("postViewMedia"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "A post's media content with alongside its dimensions data",
                        ),
                    ),
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("fullsizeUrl"),
                            ::jacquard_common::smol_str::SmolStr::new_static("thumbnailUrl"),
                            ::jacquard_common::smol_str::SmolStr::new_static("mimeType"),
                            ::jacquard_common::smol_str::SmolStr::new_static("dimensions")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::alloc::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("alt"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "dimensions",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static(
                                    "#postViewMediaDimensions",
                                ),
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "fullsizeUrl",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Uri,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("mimeType"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "thumbnailUrl",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Uri,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static(
                    "postViewMediaDimensions",
                ),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "Width and height of a post's media.",
                        ),
                    ),
                    required: Some(
                        vec![
                            ::jacquard_common::smol_str::SmolStr::new_static("width"),
                            ::jacquard_common::smol_str::SmolStr::new_static("height")
                        ],
                    ),
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::alloc::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("height"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                description: None,
                                default: None,
                                minimum: None,
                                maximum: None,
                                r#enum: None,
                                r#const: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("width"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                description: None,
                                default: None,
                                minimum: None,
                                maximum: None,
                                r#enum: None,
                                r#const: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("viewerState"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "Metadata about the requesting account's relationship with the subject content. Only has meaningful content for authed requests.",
                        ),
                    ),
                    required: None,
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::alloc::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "favourite",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: None,
                                format: Some(
                                    ::jacquard_lexicon::lexicon::LexStringFormat::Tid,
                                ),
                                default: None,
                                min_length: None,
                                max_length: None,
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map
        },
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for PostFeedView<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.feed.defs"
    }
    fn def_name() -> &'static str {
        "postFeedView"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_feed_defs()
    }
    fn validate(
        &self,
    ) -> ::core::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

/// Detailed view of a post, including author information and engagement metrics.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct PostView<'a> {
    #[serde(borrow)]
    pub author: crate::net_gifdex::actor::ProfileViewBasic<'a>,
    pub created_at: jacquard_common::types::string::Datetime,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub edited_at: std::option::Option<jacquard_common::types::string::Datetime>,
    pub favourite_count: i64,
    pub indexed_at: jacquard_common::types::string::Datetime,
    #[serde(borrow)]
    pub media: crate::net_gifdex::feed::PostViewMedia<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub tags: std::option::Option<Vec<jacquard_common::CowStr<'a>>>,
    #[serde(borrow)]
    pub title: jacquard_common::CowStr<'a>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub viewer: crate::net_gifdex::feed::ViewerState<'a>,
}

pub mod post_view_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Media;
        type Title;
        type Author;
        type CreatedAt;
        type FavouriteCount;
        type Uri;
        type Viewer;
        type IndexedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Media = Unset;
        type Title = Unset;
        type Author = Unset;
        type CreatedAt = Unset;
        type FavouriteCount = Unset;
        type Uri = Unset;
        type Viewer = Unset;
        type IndexedAt = Unset;
    }
    ///State transition - sets the `media` field to Set
    pub struct SetMedia<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetMedia<S> {}
    impl<S: State> State for SetMedia<S> {
        type Media = Set<members::media>;
        type Title = S::Title;
        type Author = S::Author;
        type CreatedAt = S::CreatedAt;
        type FavouriteCount = S::FavouriteCount;
        type Uri = S::Uri;
        type Viewer = S::Viewer;
        type IndexedAt = S::IndexedAt;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTitle<S> {}
    impl<S: State> State for SetTitle<S> {
        type Media = S::Media;
        type Title = Set<members::title>;
        type Author = S::Author;
        type CreatedAt = S::CreatedAt;
        type FavouriteCount = S::FavouriteCount;
        type Uri = S::Uri;
        type Viewer = S::Viewer;
        type IndexedAt = S::IndexedAt;
    }
    ///State transition - sets the `author` field to Set
    pub struct SetAuthor<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAuthor<S> {}
    impl<S: State> State for SetAuthor<S> {
        type Media = S::Media;
        type Title = S::Title;
        type Author = Set<members::author>;
        type CreatedAt = S::CreatedAt;
        type FavouriteCount = S::FavouriteCount;
        type Uri = S::Uri;
        type Viewer = S::Viewer;
        type IndexedAt = S::IndexedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Media = S::Media;
        type Title = S::Title;
        type Author = S::Author;
        type CreatedAt = Set<members::created_at>;
        type FavouriteCount = S::FavouriteCount;
        type Uri = S::Uri;
        type Viewer = S::Viewer;
        type IndexedAt = S::IndexedAt;
    }
    ///State transition - sets the `favourite_count` field to Set
    pub struct SetFavouriteCount<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetFavouriteCount<S> {}
    impl<S: State> State for SetFavouriteCount<S> {
        type Media = S::Media;
        type Title = S::Title;
        type Author = S::Author;
        type CreatedAt = S::CreatedAt;
        type FavouriteCount = Set<members::favourite_count>;
        type Uri = S::Uri;
        type Viewer = S::Viewer;
        type IndexedAt = S::IndexedAt;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUri<S> {}
    impl<S: State> State for SetUri<S> {
        type Media = S::Media;
        type Title = S::Title;
        type Author = S::Author;
        type CreatedAt = S::CreatedAt;
        type FavouriteCount = S::FavouriteCount;
        type Uri = Set<members::uri>;
        type Viewer = S::Viewer;
        type IndexedAt = S::IndexedAt;
    }
    ///State transition - sets the `viewer` field to Set
    pub struct SetViewer<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetViewer<S> {}
    impl<S: State> State for SetViewer<S> {
        type Media = S::Media;
        type Title = S::Title;
        type Author = S::Author;
        type CreatedAt = S::CreatedAt;
        type FavouriteCount = S::FavouriteCount;
        type Uri = S::Uri;
        type Viewer = Set<members::viewer>;
        type IndexedAt = S::IndexedAt;
    }
    ///State transition - sets the `indexed_at` field to Set
    pub struct SetIndexedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetIndexedAt<S> {}
    impl<S: State> State for SetIndexedAt<S> {
        type Media = S::Media;
        type Title = S::Title;
        type Author = S::Author;
        type CreatedAt = S::CreatedAt;
        type FavouriteCount = S::FavouriteCount;
        type Uri = S::Uri;
        type Viewer = S::Viewer;
        type IndexedAt = Set<members::indexed_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `media` field
        pub struct media(());
        ///Marker type for the `title` field
        pub struct title(());
        ///Marker type for the `author` field
        pub struct author(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `favourite_count` field
        pub struct favourite_count(());
        ///Marker type for the `uri` field
        pub struct uri(());
        ///Marker type for the `viewer` field
        pub struct viewer(());
        ///Marker type for the `indexed_at` field
        pub struct indexed_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct PostViewBuilder<'a, S: post_view_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<crate::net_gifdex::actor::ProfileViewBasic<'a>>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<crate::net_gifdex::feed::PostViewMedia<'a>>,
        ::core::option::Option<Vec<jacquard_common::CowStr<'a>>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
        ::core::option::Option<crate::net_gifdex::feed::ViewerState<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> PostView<'a> {
    /// Create a new builder for this type
    pub fn new() -> PostViewBuilder<'a, post_view_state::Empty> {
        PostViewBuilder::new()
    }
}

impl<'a> PostViewBuilder<'a, post_view_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::Author: post_view_state::IsUnset,
{
    /// Set the `author` field (required)
    pub fn author(
        mut self,
        value: impl Into<crate::net_gifdex::actor::ProfileViewBasic<'a>>,
    ) -> PostViewBuilder<'a, post_view_state::SetAuthor<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::CreatedAt: post_view_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> PostViewBuilder<'a, post_view_state::SetCreatedAt<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: post_view_state::State> PostViewBuilder<'a, S> {
    /// Set the `editedAt` field (optional)
    pub fn edited_at(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Datetime>>,
    ) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `editedAt` field to an Option value (optional)
    pub fn maybe_edited_at(
        mut self,
        value: Option<jacquard_common::types::string::Datetime>,
    ) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::FavouriteCount: post_view_state::IsUnset,
{
    /// Set the `favouriteCount` field (required)
    pub fn favourite_count(
        mut self,
        value: impl Into<i64>,
    ) -> PostViewBuilder<'a, post_view_state::SetFavouriteCount<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::IndexedAt: post_view_state::IsUnset,
{
    /// Set the `indexedAt` field (required)
    pub fn indexed_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> PostViewBuilder<'a, post_view_state::SetIndexedAt<S>> {
        self.__unsafe_private_named.4 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::Media: post_view_state::IsUnset,
{
    /// Set the `media` field (required)
    pub fn media(
        mut self,
        value: impl Into<crate::net_gifdex::feed::PostViewMedia<'a>>,
    ) -> PostViewBuilder<'a, post_view_state::SetMedia<S>> {
        self.__unsafe_private_named.5 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: post_view_state::State> PostViewBuilder<'a, S> {
    /// Set the `tags` field (optional)
    pub fn tags(
        mut self,
        value: impl Into<Option<Vec<jacquard_common::CowStr<'a>>>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value.into();
        self
    }
    /// Set the `tags` field to an Option value (optional)
    pub fn maybe_tags(
        mut self,
        value: Option<Vec<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value;
        self
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::Title: post_view_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> PostViewBuilder<'a, post_view_state::SetTitle<S>> {
        self.__unsafe_private_named.7 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::Uri: post_view_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> PostViewBuilder<'a, post_view_state::SetUri<S>> {
        self.__unsafe_private_named.8 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::Viewer: post_view_state::IsUnset,
{
    /// Set the `viewer` field (required)
    pub fn viewer(
        mut self,
        value: impl Into<crate::net_gifdex::feed::ViewerState<'a>>,
    ) -> PostViewBuilder<'a, post_view_state::SetViewer<S>> {
        self.__unsafe_private_named.9 = ::core::option::Option::Some(value.into());
        PostViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewBuilder<'a, S>
where
    S: post_view_state::State,
    S::Media: post_view_state::IsSet,
    S::Title: post_view_state::IsSet,
    S::Author: post_view_state::IsSet,
    S::CreatedAt: post_view_state::IsSet,
    S::FavouriteCount: post_view_state::IsSet,
    S::Uri: post_view_state::IsSet,
    S::Viewer: post_view_state::IsSet,
    S::IndexedAt: post_view_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> PostView<'a> {
        PostView {
            author: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            edited_at: self.__unsafe_private_named.2,
            favourite_count: self.__unsafe_private_named.3.unwrap(),
            indexed_at: self.__unsafe_private_named.4.unwrap(),
            media: self.__unsafe_private_named.5.unwrap(),
            tags: self.__unsafe_private_named.6,
            title: self.__unsafe_private_named.7.unwrap(),
            uri: self.__unsafe_private_named.8.unwrap(),
            viewer: self.__unsafe_private_named.9.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> PostView<'a> {
        PostView {
            author: self.__unsafe_private_named.0.unwrap(),
            created_at: self.__unsafe_private_named.1.unwrap(),
            edited_at: self.__unsafe_private_named.2,
            favourite_count: self.__unsafe_private_named.3.unwrap(),
            indexed_at: self.__unsafe_private_named.4.unwrap(),
            media: self.__unsafe_private_named.5.unwrap(),
            tags: self.__unsafe_private_named.6,
            title: self.__unsafe_private_named.7.unwrap(),
            uri: self.__unsafe_private_named.8.unwrap(),
            viewer: self.__unsafe_private_named.9.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for PostView<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.feed.defs"
    }
    fn def_name() -> &'static str {
        "postView"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_feed_defs()
    }
    fn validate(
        &self,
    ) -> ::core::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

/// A post's media content with alongside its dimensions data
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct PostViewMedia<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub alt: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(borrow)]
    pub dimensions: crate::net_gifdex::feed::PostViewMediaDimensions<'a>,
    #[serde(borrow)]
    pub fullsize_url: jacquard_common::types::string::Uri<'a>,
    #[serde(borrow)]
    pub mime_type: jacquard_common::CowStr<'a>,
    #[serde(borrow)]
    pub thumbnail_url: jacquard_common::types::string::Uri<'a>,
}

pub mod post_view_media_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type ThumbnailUrl;
        type MimeType;
        type Dimensions;
        type FullsizeUrl;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type ThumbnailUrl = Unset;
        type MimeType = Unset;
        type Dimensions = Unset;
        type FullsizeUrl = Unset;
    }
    ///State transition - sets the `thumbnail_url` field to Set
    pub struct SetThumbnailUrl<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetThumbnailUrl<S> {}
    impl<S: State> State for SetThumbnailUrl<S> {
        type ThumbnailUrl = Set<members::thumbnail_url>;
        type MimeType = S::MimeType;
        type Dimensions = S::Dimensions;
        type FullsizeUrl = S::FullsizeUrl;
    }
    ///State transition - sets the `mime_type` field to Set
    pub struct SetMimeType<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetMimeType<S> {}
    impl<S: State> State for SetMimeType<S> {
        type ThumbnailUrl = S::ThumbnailUrl;
        type MimeType = Set<members::mime_type>;
        type Dimensions = S::Dimensions;
        type FullsizeUrl = S::FullsizeUrl;
    }
    ///State transition - sets the `dimensions` field to Set
    pub struct SetDimensions<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDimensions<S> {}
    impl<S: State> State for SetDimensions<S> {
        type ThumbnailUrl = S::ThumbnailUrl;
        type MimeType = S::MimeType;
        type Dimensions = Set<members::dimensions>;
        type FullsizeUrl = S::FullsizeUrl;
    }
    ///State transition - sets the `fullsize_url` field to Set
    pub struct SetFullsizeUrl<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetFullsizeUrl<S> {}
    impl<S: State> State for SetFullsizeUrl<S> {
        type ThumbnailUrl = S::ThumbnailUrl;
        type MimeType = S::MimeType;
        type Dimensions = S::Dimensions;
        type FullsizeUrl = Set<members::fullsize_url>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `thumbnail_url` field
        pub struct thumbnail_url(());
        ///Marker type for the `mime_type` field
        pub struct mime_type(());
        ///Marker type for the `dimensions` field
        pub struct dimensions(());
        ///Marker type for the `fullsize_url` field
        pub struct fullsize_url(());
    }
}

/// Builder for constructing an instance of this type
pub struct PostViewMediaBuilder<'a, S: post_view_media_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<crate::net_gifdex::feed::PostViewMediaDimensions<'a>>,
        ::core::option::Option<jacquard_common::types::string::Uri<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Uri<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> PostViewMedia<'a> {
    /// Create a new builder for this type
    pub fn new() -> PostViewMediaBuilder<'a, post_view_media_state::Empty> {
        PostViewMediaBuilder::new()
    }
}

impl<'a> PostViewMediaBuilder<'a, post_view_media_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PostViewMediaBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: post_view_media_state::State> PostViewMediaBuilder<'a, S> {
    /// Set the `alt` field (optional)
    pub fn alt(mut self, value: impl Into<Option<jacquard_common::CowStr<'a>>>) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `alt` field to an Option value (optional)
    pub fn maybe_alt(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S> PostViewMediaBuilder<'a, S>
where
    S: post_view_media_state::State,
    S::Dimensions: post_view_media_state::IsUnset,
{
    /// Set the `dimensions` field (required)
    pub fn dimensions(
        mut self,
        value: impl Into<crate::net_gifdex::feed::PostViewMediaDimensions<'a>>,
    ) -> PostViewMediaBuilder<'a, post_view_media_state::SetDimensions<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        PostViewMediaBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewMediaBuilder<'a, S>
where
    S: post_view_media_state::State,
    S::FullsizeUrl: post_view_media_state::IsUnset,
{
    /// Set the `fullsizeUrl` field (required)
    pub fn fullsize_url(
        mut self,
        value: impl Into<jacquard_common::types::string::Uri<'a>>,
    ) -> PostViewMediaBuilder<'a, post_view_media_state::SetFullsizeUrl<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        PostViewMediaBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewMediaBuilder<'a, S>
where
    S: post_view_media_state::State,
    S::MimeType: post_view_media_state::IsUnset,
{
    /// Set the `mimeType` field (required)
    pub fn mime_type(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> PostViewMediaBuilder<'a, post_view_media_state::SetMimeType<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        PostViewMediaBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewMediaBuilder<'a, S>
where
    S: post_view_media_state::State,
    S::ThumbnailUrl: post_view_media_state::IsUnset,
{
    /// Set the `thumbnailUrl` field (required)
    pub fn thumbnail_url(
        mut self,
        value: impl Into<jacquard_common::types::string::Uri<'a>>,
    ) -> PostViewMediaBuilder<'a, post_view_media_state::SetThumbnailUrl<S>> {
        self.__unsafe_private_named.4 = ::core::option::Option::Some(value.into());
        PostViewMediaBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewMediaBuilder<'a, S>
where
    S: post_view_media_state::State,
    S::ThumbnailUrl: post_view_media_state::IsSet,
    S::MimeType: post_view_media_state::IsSet,
    S::Dimensions: post_view_media_state::IsSet,
    S::FullsizeUrl: post_view_media_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> PostViewMedia<'a> {
        PostViewMedia {
            alt: self.__unsafe_private_named.0,
            dimensions: self.__unsafe_private_named.1.unwrap(),
            fullsize_url: self.__unsafe_private_named.2.unwrap(),
            mime_type: self.__unsafe_private_named.3.unwrap(),
            thumbnail_url: self.__unsafe_private_named.4.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> PostViewMedia<'a> {
        PostViewMedia {
            alt: self.__unsafe_private_named.0,
            dimensions: self.__unsafe_private_named.1.unwrap(),
            fullsize_url: self.__unsafe_private_named.2.unwrap(),
            mime_type: self.__unsafe_private_named.3.unwrap(),
            thumbnail_url: self.__unsafe_private_named.4.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for PostViewMedia<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.feed.defs"
    }
    fn def_name() -> &'static str {
        "postViewMedia"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_feed_defs()
    }
    fn validate(
        &self,
    ) -> ::core::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

/// Width and height of a post's media.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct PostViewMediaDimensions<'a> {
    pub height: i64,
    pub width: i64,
}

pub mod post_view_media_dimensions_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Height;
        type Width;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Height = Unset;
        type Width = Unset;
    }
    ///State transition - sets the `height` field to Set
    pub struct SetHeight<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetHeight<S> {}
    impl<S: State> State for SetHeight<S> {
        type Height = Set<members::height>;
        type Width = S::Width;
    }
    ///State transition - sets the `width` field to Set
    pub struct SetWidth<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetWidth<S> {}
    impl<S: State> State for SetWidth<S> {
        type Height = S::Height;
        type Width = Set<members::width>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `height` field
        pub struct height(());
        ///Marker type for the `width` field
        pub struct width(());
    }
}

/// Builder for constructing an instance of this type
pub struct PostViewMediaDimensionsBuilder<
    'a,
    S: post_view_media_dimensions_state::State,
> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (::core::option::Option<i64>, ::core::option::Option<i64>),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> PostViewMediaDimensions<'a> {
    /// Create a new builder for this type
    pub fn new() -> PostViewMediaDimensionsBuilder<
        'a,
        post_view_media_dimensions_state::Empty,
    > {
        PostViewMediaDimensionsBuilder::new()
    }
}

impl<'a> PostViewMediaDimensionsBuilder<'a, post_view_media_dimensions_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PostViewMediaDimensionsBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewMediaDimensionsBuilder<'a, S>
where
    S: post_view_media_dimensions_state::State,
    S::Height: post_view_media_dimensions_state::IsUnset,
{
    /// Set the `height` field (required)
    pub fn height(
        mut self,
        value: impl Into<i64>,
    ) -> PostViewMediaDimensionsBuilder<
        'a,
        post_view_media_dimensions_state::SetHeight<S>,
    > {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        PostViewMediaDimensionsBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewMediaDimensionsBuilder<'a, S>
where
    S: post_view_media_dimensions_state::State,
    S::Width: post_view_media_dimensions_state::IsUnset,
{
    /// Set the `width` field (required)
    pub fn width(
        mut self,
        value: impl Into<i64>,
    ) -> PostViewMediaDimensionsBuilder<
        'a,
        post_view_media_dimensions_state::SetWidth<S>,
    > {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        PostViewMediaDimensionsBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> PostViewMediaDimensionsBuilder<'a, S>
where
    S: post_view_media_dimensions_state::State,
    S::Height: post_view_media_dimensions_state::IsSet,
    S::Width: post_view_media_dimensions_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> PostViewMediaDimensions<'a> {
        PostViewMediaDimensions {
            height: self.__unsafe_private_named.0.unwrap(),
            width: self.__unsafe_private_named.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> PostViewMediaDimensions<'a> {
        PostViewMediaDimensions {
            height: self.__unsafe_private_named.0.unwrap(),
            width: self.__unsafe_private_named.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for PostViewMediaDimensions<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.feed.defs"
    }
    fn def_name() -> &'static str {
        "postViewMediaDimensions"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_feed_defs()
    }
    fn validate(
        &self,
    ) -> ::core::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

/// Metadata about the requesting account's relationship with the subject content. Only has meaningful content for authed requests.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct ViewerState<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub favourite: std::option::Option<jacquard_common::types::string::Tid>,
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for ViewerState<'a> {
    fn nsid() -> &'static str {
        "net.gifdex.feed.defs"
    }
    fn def_name() -> &'static str {
        "viewerState"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_net_gifdex_feed_defs()
    }
    fn validate(
        &self,
    ) -> ::core::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}