// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.gifdex.feed.getPost
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetPost<'a> {
    #[serde(borrow)]
    pub actor: jacquard_common::types::string::Did<'a>,
    #[serde(borrow)]
    pub rkey: jacquard_common::CowStr<'a>,
}

pub mod get_post_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Actor;
        type Rkey;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Actor = Unset;
        type Rkey = Unset;
    }
    ///State transition - sets the `actor` field to Set
    pub struct SetActor<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetActor<S> {}
    impl<S: State> State for SetActor<S> {
        type Actor = Set<members::actor>;
        type Rkey = S::Rkey;
    }
    ///State transition - sets the `rkey` field to Set
    pub struct SetRkey<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetRkey<S> {}
    impl<S: State> State for SetRkey<S> {
        type Actor = S::Actor;
        type Rkey = Set<members::rkey>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `actor` field
        pub struct actor(());
        ///Marker type for the `rkey` field
        pub struct rkey(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetPostBuilder<'a, S: get_post_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetPost<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetPostBuilder<'a, get_post_state::Empty> {
        GetPostBuilder::new()
    }
}

impl<'a> GetPostBuilder<'a, get_post_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetPostBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetPostBuilder<'a, S>
where
    S: get_post_state::State,
    S::Actor: get_post_state::IsUnset,
{
    /// Set the `actor` field (required)
    pub fn actor(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> GetPostBuilder<'a, get_post_state::SetActor<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetPostBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetPostBuilder<'a, S>
where
    S: get_post_state::State,
    S::Rkey: get_post_state::IsUnset,
{
    /// Set the `rkey` field (required)
    pub fn rkey(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> GetPostBuilder<'a, get_post_state::SetRkey<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        GetPostBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetPostBuilder<'a, S>
where
    S: get_post_state::State,
    S::Actor: get_post_state::IsSet,
    S::Rkey: get_post_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetPost<'a> {
        GetPost {
            actor: self.__unsafe_private_named.0.unwrap(),
            rkey: self.__unsafe_private_named.1.unwrap(),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetPostOutput<'a> {
    #[serde(borrow)]
    pub post: crate::net_gifdex::feed::PostView<'a>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum GetPostError<'a> {
    /// The requested post does not exist or has not been indexed yet.
    #[serde(rename = "PostNotFound")]
    PostNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for GetPostError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::PostNotFound(msg) => {
                write!(f, "PostNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///net.gifdex.feed.getPost
pub struct GetPostResponse;
impl jacquard_common::xrpc::XrpcResp for GetPostResponse {
    const NSID: &'static str = "net.gifdex.feed.getPost";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetPostOutput<'de>;
    type Err<'de> = GetPostError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetPost<'a> {
    const NSID: &'static str = "net.gifdex.feed.getPost";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetPostResponse;
}

/// Endpoint type for
///net.gifdex.feed.getPost
pub struct GetPostRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetPostRequest {
    const PATH: &'static str = "/xrpc/net.gifdex.feed.getPost";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetPost<'de>;
    type Response = GetPostResponse;
}