// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.gifdex.feed.getPostsByQuery
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GetPostsByQuerySortBy {
    Newest,
    Oldest,
    Top,
    Relevance,
}

impl GetPostsByQuerySortBy {
    /// Returns the string representation of this enum variant.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Newest => "newest",
            Self::Oldest => "oldest",
            Self::Top => "top",
            Self::Relevance => "relevance",
        }
    }
}

impl core::str::FromStr for GetPostsByQuerySortBy {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "newest" => Ok(Self::Newest),
            "oldest" => Ok(Self::Oldest),
            "top" => Ok(Self::Top),
            "relevance" => Ok(Self::Relevance),
            _ => {
                Err(
                    format!(
                        "invalid value '{}', expected one of: {}", s,
                        "newest, oldest, top, relevance"
                    ),
                )
            }
        }
    }
}

impl TryFrom<&str> for GetPostsByQuerySortBy {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        s.parse()
    }
}

impl core::fmt::Display for GetPostsByQuerySortBy {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl AsRef<str> for GetPostsByQuerySortBy {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl serde::Serialize for GetPostsByQuerySortBy {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for GetPostsByQuerySortBy {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&str>::deserialize(deserializer)?;
        s.parse().map_err(serde::de::Error::custom)
    }
}

impl jacquard_common::IntoStatic for GetPostsByQuerySortBy {
    type Output = Self;
    fn into_static(self) -> Self::Output {
        self
    }
}

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetPostsByQuery<'a> {
    #[serde(borrow)]
    pub actor: jacquard_common::types::string::Did<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub cursor: std::option::Option<i64>,
    ///(default: 50, min: 1, max: 100)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub query: std::option::Option<jacquard_common::CowStr<'a>>,
    ///(default: "relevance")
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub sort_by: std::option::Option<GetPostsByQuerySortBy>,
}

pub mod get_posts_by_query_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Actor;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Actor = Unset;
    }
    ///State transition - sets the `actor` field to Set
    pub struct SetActor<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetActor<S> {}
    impl<S: State> State for SetActor<S> {
        type Actor = Set<members::actor>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `actor` field
        pub struct actor(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetPostsByQueryBuilder<'a, S: get_posts_by_query_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<i64>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetPostsByQuery<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetPostsByQueryBuilder<'a, get_posts_by_query_state::Empty> {
        GetPostsByQueryBuilder::new()
    }
}

impl<'a> GetPostsByQueryBuilder<'a, get_posts_by_query_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetPostsByQueryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetPostsByQueryBuilder<'a, S>
where
    S: get_posts_by_query_state::State,
    S::Actor: get_posts_by_query_state::IsUnset,
{
    /// Set the `actor` field (required)
    pub fn actor(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> GetPostsByQueryBuilder<'a, get_posts_by_query_state::SetActor<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetPostsByQueryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: get_posts_by_query_state::State> GetPostsByQueryBuilder<'a, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S: get_posts_by_query_state::State> GetPostsByQueryBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S: get_posts_by_query_state::State> GetPostsByQueryBuilder<'a, S> {
    /// Set the `query` field (optional)
    pub fn query(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.3 = value.into();
        self
    }
    /// Set the `query` field to an Option value (optional)
    pub fn maybe_query(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.3 = value;
        self
    }
}

impl<'a, S: get_posts_by_query_state::State> GetPostsByQueryBuilder<'a, S> {
    /// Set the `sortBy` field (optional)
    pub fn sort_by(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value.into();
        self
    }
    /// Set the `sortBy` field to an Option value (optional)
    pub fn maybe_sort_by(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.4 = value;
        self
    }
}

impl<'a, S> GetPostsByQueryBuilder<'a, S>
where
    S: get_posts_by_query_state::State,
    S::Actor: get_posts_by_query_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetPostsByQuery<'a> {
        GetPostsByQuery {
            actor: self.__unsafe_private_named.0.unwrap(),
            cursor: self.__unsafe_private_named.1,
            limit: self.__unsafe_private_named.2,
            query: self.__unsafe_private_named.3,
            sort_by: self.__unsafe_private_named.4,
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetPostsByQueryOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub cursor: std::option::Option<i64>,
    #[serde(borrow)]
    pub feed: Vec<crate::net_gifdex::feed::PostFeedView<'a>>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum GetPostsByQueryError<'a> {
    /// The requested actor does not exist or has not been indexed yet.
    #[serde(rename = "ActorNotFound")]
    ActorNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for GetPostsByQueryError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::ActorNotFound(msg) => {
                write!(f, "ActorNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///net.gifdex.feed.getPostsByQuery
pub struct GetPostsByQueryResponse;
impl jacquard_common::xrpc::XrpcResp for GetPostsByQueryResponse {
    const NSID: &'static str = "net.gifdex.feed.getPostsByQuery";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetPostsByQueryOutput<'de>;
    type Err<'de> = GetPostsByQueryError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetPostsByQuery<'a> {
    const NSID: &'static str = "net.gifdex.feed.getPostsByQuery";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetPostsByQueryResponse;
}

/// Endpoint type for
///net.gifdex.feed.getPostsByQuery
pub struct GetPostsByQueryRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetPostsByQueryRequest {
    const PATH: &'static str = "/xrpc/net.gifdex.feed.getPostsByQuery";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetPostsByQuery<'de>;
    type Response = GetPostsByQueryResponse;
}